# Generated by Django 3.1.7 on 2022-01-12 07:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to=products.models.user_directory_image_path),
            preserve_default=False,
        ),
    ]
